sign-tag = true
shared-version = true
consolidate-commits = false
pre-release-commit-message = "[{{crate_name}}] version {{version}}"
tag-message = "[{{crate_name}}] version {{version}}"
tag-name = "{{crate_name}}-{{version}}"
publish = false
dependent-version = "upgrade"
pre-release-replacements = [
    {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
]
